### ISSUE TITLE
Remove dependency on active_attr

### ISSUE THREAD

**Issue by darryldaniel** [Investec-Developer-Community/investec_open_api#18]
At the moment, this gem depends on `active_attr` for it's models. `active_attr` has dependencies on `actionpack`, `activemodel` and `activesupport`. There's 2 problems with this at the moment:
1. These are pretty heavy dependencies for this gem. Especially if you're not building in a rails context.
2. `active_attr` has fallen behind in keeping these dependencies up to date which means that this gem is incompatible with Rails 7.1.1.

I'm not sure that we absolutely need all of the functionality required from `active_attr` and I think I could replace it with `OpenStruct` (or something equivalent). However, I also realise that it's possible that there's something specific that people are using from `active_attr` so if that's the case, could we discuss further?

**Comment by programmable-banking-community** [comment]
Thanks for raising this excellent point, @darryldaniel! We'll look into this and revert to get your input once we've discussed this further. Thanks!

**Comment by dominicsanto** [comment]
@darryldaniel sorry for the late reply on this. I think best approach might be to open up a PR for this change and see how it impacts everything?

Also happy to pair on this work with you if you need

**Comment by stevebissett** [comment]
@dominicsanto - I've started taking a stab at this as I'm using this in a Ruby project outside of Rails. 
It's probably going to take some time to get to, but I'm looking at a few goals in this [fork](https://github.com/stevebissett/investec_open_api_ruby/tree/remove-attr) (which can be brought back if they meet the goals of the original client)

- Remove the need for `active_attr` (replace with `dry-struct`) 
- Add some stricter validation on the models. 
- Expand the functionality to aspects of the cards API (https://github.com/Investec-Developer-Community/investec_open_api/issues/21), everything except for modifying function code. 
- Expand functionality to include listing and retrieval of documents.

**Comment by darryldaniel** [comment]
This issue has been resolved in version 2.0.0 of this gem.
